# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 67e5f1c8e854559f95a91778f50d05cc28e9d813c7ab99838eb1c4f3e254a3f984644d6d65572fc0cc7e335952188967381e61308f71eee4f0840ef29a18b178

test:
  secret_key_base: b58b55be474f6697ffc75811da7783a6f97c5cfb12d0a5a221f6f20e9d65dff90805c6035b89970dd91c472e648949a71037311ba4819e186e5ecc0a7c1b60e3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
